### Obtener Todos los Estudiantes
GET http://127.0.0.1:8000/api/estudiantes
Content-Type: application/json

###

### Crear Estudiante
POST http://127.0.0.1:8000/api/estudiantes
Content-Type: application/json

{
    "cod": "5522",
    "nombres": "usuario",
    "email": "usuario@email.com"
}

###

### Obtener Estudiante por ID
GET http://127.0.0.1:8000/api/estudiantes/1234
Content-Type: application/json

###

### Actualizar Estudiante
PUT http://127.0.0.1:8000/api/estudiantes/3333
Content-Type: application/json

{
    "cod": "3333",
    "nombres": "Juan diego Castillo",
    "email": "juandiego@email.com"
}

###

### Eliminar Estudiante
DELETE http://127.0.0.1:8000/api/estudiantes/3333
Content-Type: application/json


### Listar todas las notas
GET http://127.0.0.1:8000/api/notas
Accept: application/json

###

### Crear una nueva nota
POST http://127.0.0.1:8000/api/notas
Content-Type: application/json
Accept: application/json

{
  "actividad": "Proyecto prueba 2",
  "nota": 2.0,
  "codEstudiante": 1111
}

###

### Ver una nota específica
GET http://127.0.0.1:8000/api/notas/2
Accept: application/json

###

### Actualizar una nota existente
PUT http://127.0.0.1:8000/api/notas/2
Content-Type: application/json
Accept: application/json

{
  "actividad": "Proyecto Final Modificado",
  "nota": 3.8,
  "codEstudiante": 1234
}

###

### Eliminar una nota
DELETE http://127.0.0.1:8000/api/notas/5
Accept: application/json

### Resumen de estudiantes
GET http://127.0.0.1:8000/api/estudiantes/resumen
Content-Type: application/json

###

### Resumen de notas
GET http://127.0.0.1:8000/api/notas/resumen
Content-Type: application/json

